name: 'Generate SSH Key'

on: [push]

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate SSH Key
      run: |
        ssh-keygen -t rsa -b 4096 -C "${{ github.event.inputs.email }}" -f "${{ inputs.path }}" -N ""
        echo "SSH public key generated:"
        cat "${{ inputs.path }}.pub"
        path:
          description: 'Path to save the SSH private key'
          default: '~/.ssh/id_rsa'
