name: 'Generate SSH Key'

on: [push]

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate SSH Key
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -C "${{ github.event.inputs.email }}" -f ~/.ssh/id_rsa -N ""
        echo "SSH public key generated:"
        cat ~/.ssh/id_rsa.pub
      env:
        EMAIL: ${{ github.event.inputs.email }}
